<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <link rel="icon">
    <link rel="stylesheet" href="https://sats.capetown/wp-content/maintenance/styles.css">
    <script src="https://sats.capetown/wp-content/maintenance/timer.js"></script>
    <title></title>
</head>

<body>

    <div class="container">

    <header class="header">
        <h1></h1>
        <h2></h2>
    </header>

    <!--START_TIMER_BLOCK-->
        <!--END_TIMER_BLOCK-->

    <!--START_SOCIAL_LINKS_BLOCK-->
    <section class="social-links">
            </section>
    <!--END_SOCIAL_LINKS_BLOCK-->

</div>

<footer class="footer">
    <div class="footer__content">
            </div>
</footer>

</body>
</html>